= How to be more productive

:hp-tags: work flow, 

== Routines and Willpower

In scientific psychology articles you can read a lot of willpower.
Willpower is a resource which is consumed whenever we force ourself to do s.th. we don't like. 
So their result to be more productive is to do the important work at the first place when you have enough willpower to do it.
This seems logical and definitly will help you being more productive.
BUT their is one this which is not mentioned enough:
There is a huge difference in the way you do the unlikly work.

E.g. let's say you want to eat more healthy, but you have some cookies directly near your workplace. So you have to force yourself all the time to not grab one and eat it. After a time this forcing will have consumed all your willpower and at the end the cookie-monster has been fed up.
In an other way you could only force yourself ones in the supermarket to not buy some cookies. When you'r at your workplace or whatever and you don't have any unhealthy stuff around you, you don't have a big choose. There are no cookies in your eye-view and you don't have to work so hard against your inner cookie-monster. It also could help a lot to just but the cookies in a cabinet, to have it out of your mind. 

Same thing can be applied to our goals we want to meet.
It can help a lot to create a workplace without any obstacles.
This is for me also the reason why I am more productive when I work in the Library than at my "home-office" with all the games installed on my pc, tv and radio around me, easier tasks which could be done - like cleaning up my flat, and so on and so on.